services:
    menumodule.form.type.item_tree:
        class: SmartCore\Module\Menu\Form\Tree\ItemTreeType
        arguments: [ '@doctrine' ]
        tags:
            - { name: form.type, alias: smart_module_menu_item_tree }
